nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.6.1.cjs

npmRegistryServer: https://npm.pkg.github.com/

npmScopes:
  zenkigen:
    npmAlwaysAuth: true
    npmRegistryServer: https://npm.pkg.github.com/
    npmPublishRegistry: https://npm.pkg.github.com/
    npmAuthToken: ${{ NODE_AUTH_TOKEN }}
