nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-4.0.1.cjs

npmScopes:
  zenkigen-inc:
    npmAuthToken: ${NODE_AUTH_TOKEN-}
