name: 'Chromatic'

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - '!renovate/**'
      - '!dependabot/**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install
      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Storybook Preview

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## chromatic

            ### Outputs
            | Name | Value |
            |---|---|
            | storybookUrl | ${{ steps.chromatic.outputs.storybookUrl }} |
            | buildUrl | ${{ steps.chromatic.outputs.buildUrl }} |
            | actualCaptureCount | ${{ steps.chromatic.outputs.actualCaptureCount }} |
            | changeCount | ${{ steps.chromatic.outputs.changeCount }} |
            | errorCount | ${{ steps.chromatic.outputs.errorCount }} |
          edit-mode: replace
