name: Publish npm package

on:
  workflow_run:
    workflows: ['Check syntax']
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: yarn install

      - name: Build npm package
        run: yarn build

      - name: Publish npm package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
